# Loading data into Pandas

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data_folder = "/home/alfonsbc/Untitled Folder/Temperatura_Promedio_Excel/"
Y = [0]*35 #Paths to every single excel document
for i in range(35):
    Y[i] = data_folder + str(1985 + i) + "Tmed.xlsx"

for j in range(35):
    dfj = pd.read_excel(Y[j])

## Reading Data in Pandas

In [8]:
data_folder = "/home/alfonsbc/Untitled Folder/Temperatura_Promedio_Excel/"
Y = [0]*35 #Paths to every single excel document
for i in range(35):
    Y[i] = data_folder + str(1985 + i) + "Tmed.xlsx"

df0 = pd.read_excel(Y[0])
df1 = pd.read_excel(Y[1])
df2 = pd.read_excel(Y[2])
df3 = pd.read_excel(Y[3])
df4 = pd.read_excel(Y[4])
df5 = pd.read_excel(Y[5])
df6 = pd.read_excel(Y[6])
df7 = pd.read_excel(Y[7])
df8 = pd.read_excel(Y[8])
df9 = pd.read_excel(Y[9])
df10 = pd.read_excel(Y[10])
df11 = pd.read_excel(Y[11])
df12 = pd.read_excel(Y[12])
df13 = pd.read_excel(Y[13])
df14 = pd.read_excel(Y[14])
df15 = pd.read_excel(Y[15])
df16 = pd.read_excel(Y[16])
df17 = pd.read_excel(Y[17])
df18 = pd.read_excel(Y[18])
df19 = pd.read_excel(Y[19])
df20 = pd.read_excel(Y[20])
df21 = pd.read_excel(Y[21])
df22 = pd.read_excel(Y[22])
df23 = pd.read_excel(Y[23])
df24 = pd.read_excel(Y[24])
df25 = pd.read_excel(Y[25])
df26 = pd.read_excel(Y[26])
df27 = pd.read_excel(Y[27])
df28 = pd.read_excel(Y[28])
df29 = pd.read_excel(Y[29])
df30 = pd.read_excel(Y[30])
df31 = pd.read_excel(Y[31])
df32 = pd.read_excel(Y[32])
df33 = pd.read_excel(Y[33])
df34 = pd.read_excel(Y[34])

AGS0 = [0]*6
for i in range(6):
    AGS0[i] = df0.iloc[1,i+1]
print(AGS0)
#WINTER
print("WINTER")
AGS0_n = [0]*3
for i in range(3):
    AGS0_n[i] = df0.iloc[1,i+1]
print(AGS0_n)
AGS1_n = [0]*3
for i in range(3):
    AGS1_n[i] = df1.iloc[1,i+1]
print(AGS1_n)
AGS2_n = [0]*3
for i in range(3):
    AGS2_n[i] = df2.iloc[1,i+1]
print(AGS2_n)
AGS3_n = [0]*3
for i in range(3):
    AGS3_n[i] = df3.iloc[1,i+1]
print(AGS3_n)
AGS4_n = [0]*3
for i in range(3):
    AGS4_n[i] = df4.iloc[1,i+1]
print(AGS4_n)
AGS5_n = [0]*3
for i in range(3):
    AGS5_n[i] = df5.iloc[1,i+1]
print(AGS5_n)
AGS6_n = [0]*3
for i in range(3):
    AGS6_n[i] = df6.iloc[1,i+1]
print(AGS6_n)
AGS7_n = [0]*3
for i in range(3):
    AGS7_n[i] = df7.iloc[1,i+1]
print(AGS7_n)
AGS8_n = [0]*3
for i in range(3):
    AGS8_n[i] = df8.iloc[1,i+1]
print(AGS8_n)
AGS9_n = [0]*3
for i in range(3):
    AGS9_n[i] = df9.iloc[1,i+1]
print(AGS9_n)
print("\n\n")
Wi = AGS0_n+AGS1_n+AGS2_n
Win = AGS0_n+AGS1_n+AGS2_n+AGS3_n+AGS4_n
Wint = AGS0_n+AGS1_n+AGS2_n+AGS3_n+AGS4_n+AGS5_n+AGS6_n+AGS7_n+AGS8_n+AGS9_n
Q = np.array([AGS0_n,AGS1_n,AGS2_n])
QR = np.array([AGS0_n,AGS1_n,AGS2_n,AGS3_n,AGS4_n])
QRL = np.array([AGS0_n,AGS1_n,AGS2_n,AGS3_n,AGS4_n,AGS5_n,AGS6_n,AGS7_n,AGS8_n,AGS9_n])
#print(Q, "\n\n" ,QR)
print("This is the mean of first three years : ",np.mean(Q), "\n")
print("This is the mean of first five years: ",np.mean(QR), "\n")
print("This is the mean of first ten years: ",np.mean(QRL), "\n")
#SPRING
print("SPRING")
AGS0_p = [0]*3
for i in range(3):
    AGS0_p[i] = df0.iloc[1,i+4]
print(AGS0_p)
AGS1_p = [0]*3
for i in range(3):
    AGS1_p[i] = df1.iloc[1,i+4]
print(AGS1_p)
AGS2_p = [0]*3
for i in range(3):
    AGS2_p[i] = df2.iloc[1,i+4]
print(AGS2_p)
AGS3_p = [0]*3
for i in range(3):
    AGS3_p[i] = df3.iloc[1,i+4]
print(AGS3_p)
AGS4_p = [0]*3
for i in range(3):
    AGS4_p[i] = df4.iloc[1,i+4]
print(AGS4_p)
AGS5_p = [0]*3
for i in range(3):
    AGS5_p[i] = df5.iloc[1,i+4]
print(AGS5_p)
AGS6_p = [0]*3
for i in range(3):
    AGS6_p[i] = df6.iloc[1,i+4]
print(AGS6_p)
AGS7_p = [0]*3
for i in range(3):
    AGS7_p[i] = df7.iloc[1,i+4]
print(AGS7_p)
AGS8_p = [0]*3
for i in range(3):
    AGS8_p[i] = df8.iloc[1,i+4]
print(AGS8_p)
AGS9_p = [0]*3
for i in range(3):
    AGS9_p[i] = df9.iloc[1,i+4]
print(AGS9_p)
print("\n\n")
Sp = AGS0_p + AGS1_p+AGS2_p
Spr = AGS0_p + AGS1_p+AGS2_p+AGS3_p+AGS4_p
Spri = AGS0_p + AGS1_p+AGS2_p+AGS3_p+AGS4_p +AGS5_p + AGS6_p+AGS7_p+AGS8_p+AGS9_p
W = np.array([AGS0_p,AGS1_p,AGS2_p])
WR = np.array([AGS0_p,AGS1_p,AGS2_p,AGS3_p,AGS4_p])
WRL = np.array([AGS0_p,AGS1_p,AGS2_p,AGS3_p,AGS4_p,AGS5_p,AGS6_p,AGS7_p,AGS8_p,AGS9_p])
#print(W, "\n\n" ,WR)
print("This is the mean of first three years : ",np.mean(W), "\n")
print("This is the mean of first five years : ",np.mean(WR), "\n")
print("This is the mean of first ten years : ",np.mean(WRL), "\n")
#SUMMER
print("SUMMER")
AGS0_v = [0]*3
for i in range(3):
    AGS0_v[i] = df0.iloc[1,i+7]
print(AGS0_v)
AGS1_v = [0]*3
for i in range(3):
    AGS1_v[i] = df1.iloc[1,i+7]
print(AGS1_v)
AGS2_v = [0]*3
for i in range(3):
    AGS2_v[i] = df2.iloc[1,i+7]
print(AGS2_v)
AGS3_v = [0]*3
for i in range(3):
    AGS3_v[i] = df3.iloc[1,i+7]
print(AGS3_v)
AGS4_v = [0]*3
for i in range(3):
    AGS4_v[i] = df4.iloc[1,i+7]
print(AGS4_v)
AGS5_v = [0]*3
for i in range(3):
    AGS5_v[i] = df5.iloc[1,i+7]
print(AGS5_v)
AGS6_v = [0]*3
for i in range(3):
    AGS6_v[i] = df6.iloc[1,i+7]
print(AGS6_v)
AGS7_v = [0]*3
for i in range(3):
    AGS7_v[i] = df7.iloc[1,i+7]
print(AGS7_v)
AGS8_v = [0]*3
for i in range(3):
    AGS8_v[i] = df8.iloc[1,i+7]
print(AGS8_v)
AGS9_v = [0]*3
for i in range(3):
    AGS9_v[i] = df9.iloc[1,i+7]
print(AGS9_v)
print("\n\n")
E = np.array([AGS0_v,AGS1_v,AGS2_v])
ER = np.array([AGS0_v,AGS1_v,AGS2_v,AGS3_v,AGS4_v])
ERU = np.array([AGS0_v,AGS1_v,AGS2_v,AGS3_v,AGS4_v,AGS5_v,AGS6_v,AGS7_v,AGS8_v,AGS9_v])
Su = AGS0_v + AGS1_v + AGS2_v
Sum = AGS0_v + AGS1_v + AGS2_v + AGS3_v +AGS4_v
Summ = AGS0_v + AGS1_v + AGS2_v + AGS3_v +AGS4_v + AGS5_v + AGS6_v + AGS7_v + AGS8_v +AGS9_v
#print(E, "\n\n" ,ER)
print("This is the mean of first three years : ",np.mean(E), "\n")
print("This is the mean of first five years: ",np.mean(ER), "\n")
print("This is the mean of first ften years : ",np.mean(ERU), "\n")
#AUTUMN/FALL
print("FALL")
AGS03 = [0]*3
for i in range(3):
    AGS03[i] = df0.iloc[1,i+10]
print(AGS03)
AGS13 = [0]*3
for i in range(3):
    AGS13[i] = df1.iloc[1,i+10]
print(AGS13)
AGS23 = [0]*3
for i in range(3):
    AGS23[i] = df2.iloc[1,i+10]
print(AGS23)
AGS33 = [0]*3
for i in range(3):
    AGS33[i] = df3.iloc[1,i+10]
print(AGS33)
AGS43 = [0]*3
for i in range(3):
    AGS43[i] = df4.iloc[1,i+10]
print(AGS43)
AGS53 = [0]*3
for i in range(3):
    AGS53[i] = df5.iloc[1,i+10]
print(AGS53)
AGS63 = [0]*3
for i in range(3):
    AGS63[i] = df6.iloc[1,i+10]
print(AGS63)
AGS73 = [0]*3
for i in range(3):
    AGS73[i] = df7.iloc[1,i+10]
print(AGS73)
AGS83 = [0]*3
for i in range(3):
    AGS83[i] = df8.iloc[1,i+10]
print(AGS83)
AGS93 = [0]*3
for i in range(3):
    AGS93[i] = df9.iloc[1,i+10]
print(AGS93)
Au = AGS03 +AGS13 +AGS23
Aut = AGS03 +AGS13 +AGS23 +AGS33 +AGS43 
Autu = AGS03 +AGS13 +AGS23 +AGS33 +AGS43+ AGS53 +AGS63 +AGS73 +AGS83 +AGS93 
R = np.array([AGS03,AGS13,AGS23])
RR = np.array([AGS03,AGS13,AGS23,AGS33,AGS43])
RRR = np.array([AGS03,AGS13,AGS23,AGS33,AGS43,AGS53,AGS63,AGS73,AGS83,AGS93])
#print(R, "\n\n" ,RR)
print("This is the mean of first three years : ",np.mean(R), "\n")
print("This is the mean of first five years : ",np.mean(RR), "\n")
print("This is the mean of first ten years : ",np.mean(RRR), "\n")
##############
# AGS1 = [0]*12
# for i in range(12):
#     AGS1[i] = df1.iloc[1,i+1]
# print(AGS1)

# AGS2 = [0]*12
# for i in range(12):
#     AGS2[i] = df2.iloc[1,i+1]
# print(AGS2)
# AGS3 = [0]*12
# for i in range(12):
#     AGS3[i] = df3.iloc[1,i+1]
# print(AGS3)
# AGS4 = [0]*12
# for i in range(12):
#     AGS4[i] = df4.iloc[1,i+1]


[11.967093779413023, 14.325850093302922, 17.05189205955335, 17.757924528301892, 21.183228911367053, 19.55581761006289]
WINTER
[11.967093779413023, 14.325850093302922, 17.05189205955335]
[12.386764042409204, 14.044454099821746, 14.679090909090903]
[11.714552315963608, 13.000357142857142, 14.870146627565989]
[12.10270737327189, 15.191417359502069, 15.848572281959383]
[14.108180822856989, 14.531284340659344, 15.36041117197538]
[13.08639683505782, 13.1279651675485, 16.42311384851707]
[12.53329501138387, 14.17755994005994, 16.947706143389258]
[11.440291563275434, 12.364993302576194, 15.710483870967742]
[13.106968959220938, 14.150687581112106, 15.297596153846154]
[13.13635005973716, 15.291666666666671, 17.123864994026285]



This is the mean of first three years :  13.782244563330876 

This is the mean of first five years:  14.078851628013528 

This is the mean of first ten years:  14.170057150586269 

SPRING
[17.757924528301892, 21.183228911367053, 19.55581761006289]
[19.586172839506172, 20

In [6]:
a = np.array([0,1,2,3,4,5])
b = np.array([a ** 3, a**2 , a**1, a**0])
print(b)
print("\n")
print(b.T)

[[  0   1   8  27  64 125]
 [  0   1   4   9  16  25]
 [  0   1   2   3   4   5]
 [  1   1   1   1   1   1]]


[[  0   0   0   1]
 [  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [11]:
A = np.matmul(b ,AGS0)
print(A)

[4430.40880042 1070.18184192  284.21541149  101.84180698]


In [16]:
z = np.matmul(b,b.T)
print(z)

[[20515  4425   979   225]
 [ 4425   979   225    55]
 [  979   225    55    15]
 [  225    55    15     6]]


In [17]:
l = np.linalg.cholesky(z)
print(l)

[[143.23058333   0.           0.           0.        ]
 [ 30.89423988   4.95438614   0.           0.        ]
 [  6.83513239   2.7922289    0.69600496   0.        ]
 [  1.57089355   1.30559822   0.88678318   1.02045201]]


In [18]:
y = np.linalg.solve(l , B)
print(y)

[ 6.83513239e+00  2.79222890e+00  6.96004963e-01 -4.36649843e-15]


In [19]:
x = np.linalg.solve(l.T, y)
print(x)

[ 1.94078058e-15 -1.44313263e-14  1.00000000e+00 -4.27898457e-15]


In [64]:
def cholesky(U):
    A = np.array(U, float)
    n = np.shape(A)
    g = n[0]
    if n[0] != n[1]:
        print("La matriz no es cuadrada")
        return
    
    Q = np.linalg.eigvals(A) 
    c = 0
    for i in range(len(Q)):
        if Q[i] > 0: continue
        else:
            c = 1
            break
    if c == 1:
        print("La matriz no tiene eigenvalores positivos")
        return
    L = np.zeros_like(A)
    for j in range(g):
        for i in range(j,g):
            if (i == j):
                sumk = 0
                for k in range(j):
                    sumk += L[i,k]**2
                L[i,j] = np.sqrt(A[i,j] - sumk)
            else:
                sumk = 0
                for k in range(j):
                    sumk += L[i,k]*L[j,k]
                L[i,j] = (A[i,j] - sumk ) / L[j,j]
    return L
                
def poli(R):
    B = np.array(R)
    n = B.shape[0]
    P = [0]*n
    for i in range(n):
        P[i] = i
    a = np.array(P)
    A = np.array([a ** 3, a**2 , a**1, a**0]).T
    #S = A^T * B
    S = np.matmul(A.T, B)
    #Z = L L^T = A^T * A
    Z = np.matmul(A.T, A)
    L = cholesky(Z)
    Y = np.linalg.solve(L,S)
    X = np.linalg.solve(L.T, Y)
    print("Los coeficientes son los siguientes: \n" , X)
    print("Para a (x^3): ", X[0], "\n")
    print("Para b (x^2): ", X[1], "\n")
    print("Para c (x): ", X[2], "\n")
    print("Para d (ind): ", X[3], "\n")
    #return X

print("Winter\n")
print(" 3 years \n")
poli(Wi)
print(" 5 years\n")
poli(Win)
print(" 10 years\n")
poli(Wint)

print("Spring\n")
print(" 3 years\n")
poli(Sp)
print(" 5 years\n")
poli(Spr)
print(" 10 years\n")
poli(Spri)

print("Summer\n")
print(" 3 years\n")
poli(Su)
print(" 5 years\n")
poli(Sum)
print(" 10 years\n")
poli(Summ)

print("Autumun\n")
print(" 3 years\n")
poli(Au)
print(" 5 years\n")
poli(Aut)
print(" 10 years\n")
poli(Autu)



# pol(AGS1)
# pol(AGS2)
# pol(AGS3)
# pol(AGS4)


Winter

 3 years 

Los coeficientes son los siguientes: 
 [ 0.08306032 -1.02747496  3.24034864 12.14959579]
Para a (x^3):  0.08306032440554365 

Para b (x^2):  -1.027474963350873 

Para c (x):  3.2403486393684213 

Para d (ind):  12.149595794078694 

 5 years

Los coeficientes son los siguientes: 
 [ 3.87096806e-03 -6.59150711e-02  3.15767719e-01  1.34835692e+01]
Para a (x^3):  0.0038709680603863125 

Para b (x^2):  -0.06591507114256182 

Para c (x):  0.3157677187086006 

Para d (ind):  13.483569219982734 

 10 years

Los coeficientes son los siguientes: 
 [ 6.41716362e-04 -2.59589551e-02  2.96547863e-01  1.32251159e+01]
Para a (x^3):  0.0006417163619538826 

Para b (x^2):  -0.025958955065966956 

Para c (x):  0.2965478627507884 

Para d (ind):  13.2251158739873 

Spring

 3 years

Los coeficientes son los siguientes: 
 [ 0.06584514 -0.81474539  2.61699813 18.09469015]
Para a (x^3):  0.06584513871980459 

Para b (x^2):  -0.8147453930443904 

Para c (x):  2.616998126463752 

Para d (ind

In [62]:
def cholesky(U):
    A = np.array(U, float)
    n = np.shape(A)
    g = n[0]
    if n[0] != n[1]:
        print("La matriz no es cuadrada")
        return
    
    Q = np.linalg.eigvals(A) 
    c = 0
    for i in range(len(Q)):
        if Q[i] > 0: continue
        else:
            c = 1
            break
    if c == 1:
        print("La matriz no tiene eigenvalores positivos")
        return
    L = np.zeros_like(A)
    for j in range(g):
        for i in range(j,g):
            if (i == j):
                sumk = 0
                for k in range(j):
                    sumk += L[i,k]**2
                L[i,j] = np.sqrt(A[i,j] - sumk)
            else:
                sumk = 0
                for k in range(j):
                    sumk += L[i,k]*L[j,k]
                L[i,j] = (A[i,j] - sumk ) / L[j,j]
    return L
                
def pol(R):
    B = np.array(R)
    n = B.shape[0]
    P = [0]*n
    for i in range(n):
        P[i] = i
    a = np.array(P)
    A = np.array([a ** 3, a**2 , a**1, a**0]).T
    #S = A^T * B
    S = np.matmul(A.T, B)
    #Z = L L^T = A^T * A
    Z = np.matmul(A.T, A)
    L = cholesky(Z)
    Y = np.linalg.solve(L,S)
    X = np.linalg.solve(L.T, Y)
    return X


def f_cholesky(W,i):
    X = pol(W) 
    return X[0]*i**3 +X[1]*i**2 +X[2]*i+X[3]

def minimos_cuadrados_1(W):
    #3 ANOS, ENTONCES I  in {1,2,3...7,8,9}
    X= []
    n = len(W)
    for i in range(n):
        X.append(f_cholesky(W,i))
    X_np = np.array(X)
    W_np = np.array(W)
    return np.sum((X_np - W_np)**2)

A = [Wi, Win, Wint,Sp, Spr, Spri, Su, Sum, Summ,Au,Aut,Autu]
#round(minimos_cuadrados_1(Autu), 3)
#Se coloca en el predict cada uno de los A[i] para obtener las predicciones

def f_predict(W):
    n = len(W)
    X = []
    for i in range(n+6):
        X.append(round(f_cholesky(W,i),2))
    return X

f_predict(Autu)

[15.93,
 15.81,
 15.69,
 15.58,
 15.48,
 15.38,
 15.29,
 15.21,
 15.13,
 15.06,
 15.0,
 14.95,
 14.91,
 14.88,
 14.86,
 14.85,
 14.85,
 14.87,
 14.9,
 14.94,
 15.0,
 15.07,
 15.15,
 15.26,
 15.37,
 15.51,
 15.66,
 15.83,
 16.02,
 16.22,
 16.45,
 16.7,
 16.96,
 17.25,
 17.56,
 17.89]